spring.application.name=escala24

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/escala24}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:escala24_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:escala24_dev_password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true